# Generated by Django 4.1.4 on 2022-12-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_shoppingcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
