# Generated by Django 4.1.4 on 2022-12-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_shoppingcart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingCart',
            new_name='ShoppingCartModel',
        ),
    ]
