# Generated by Django 4.1.4 on 2022-12-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_delete_shoppingcartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='restaurant_id',
            field=models.IntegerField(default=0),
        ),
    ]
